---
title: "Investigating Toronto COVID-19 Cases in 2020: Age group, Source of Infection, and Whether Outbreak Associated"
author: 
  - Yunkai Gu
thanks: "Code and data are available at: https://github.com/Kylie309/Toronto-2020-Covid-Cases."
date: 23 September 2024
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(opendatatoronto)
library(palmerpenguins)
```


# Introduction

You can and should cross-reference sections and sub-sections. We use @citeR and @rohan.

The remainder of this paper is structured as follows. @sec-data....


\newpage


# Data {#sec-data}


```{r}
#| label: fig-planes-1
#| fig-cap: Relationship between covid cases and age groups
#| echo: false
#| warning: false
#| message: false


analysis_data <- read_csv(here::here("data/analysis_data/covid_analysis_data.csv"))

analysis_data |> 
  ggplot(aes(x = age_group)) +
  geom_bar(stat = "count") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 5)) +
  labs(
    x = "Age Group",
    y = "Number of COVID-19 Cases"
  )

```

Talk way more about it. 


```{r}
#| label: fig-planes-2
#| fig-cap: Relationship between Covid cases and source of infection
#| echo: false
#| warning: false
#| message: false

analysis_data <- read_csv(here::here("data/analysis_data/covid_analysis_data.csv"))

analysis_data |> 
  ggplot(aes(x = source_of_infection)) +
  geom_bar(stat = "count") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 5)) +
  guides(x = guide_axis(angle = 90)) +
  labs(
    x = "Source of Infection",
    y = "Number of COVID-19 Cases"
  )

```


```{r}
#| label: fig-planes-3
#| fig-cap: Relationship between Covid cases and gender
#| echo: false
#| warning: false
#| message: false

analysis_data <- read_csv(here::here("data/analysis_data/covid_analysis_data.csv"))

analysis_data |> 
  ggplot(aes(x = client_gender)) +
  geom_bar(stat = "count") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 5)) +
  guides(x = guide_axis(angle = 90)) +
  labs(
    x = "Gender",
    y = "Number of COVID-19 Cases"
  )

```


```{r}
#| label: fig-planes-4
#| fig-cap: Relationship between covid cases and whether outbreak associated
#| echo: false
#| warning: false
#| message: false

analysis_data <- read_csv(here::here("data/analysis_data/covid_analysis_data.csv"))

analysis_data |> 
  ggplot(aes(x = outbreak_associated)) +
  geom_bar(stat = "count") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 5)) +
  guides(x = guide_axis(angle = 90)) +
  labs(
    x = "Whether outbreak associated",
    y = "Number of COVID-19 Cases"
  )

```


```{r}
#| label: fig-planes-z
#| fig-cap: Comparison of different age groups among the same source of infection
#| echo: false
#| warning: false
#| message: false

analysis_data <- read_csv(here::here("data/analysis_data/covid_analysis_data.csv"))

analysis_data |> 
  ggplot(aes(x = source_of_infection, group = age_group, fill = age_group)) +
  geom_bar(stat = "count", position = "dodge2") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 5)) +
  labs(
    x = "Source of Infection", y = "Number of COVID cases",
    fill = "Age Group",
    caption = "Data source: Open Toronto Data."
  ) +
  guides(x = guide_axis(angle = 90)) +
  scale_fill_brewer(palette = "Set1")

```


\newpage


```{r fig.height=20, fig.width=15}
#| label: fig-planes-z-1
#| fig-cap: Comparison of different age groups among the same source of infection
#| echo: false
#| warning: false
#| message: false

analysis_data <- read_csv(here::here("data/analysis_data/covid_analysis_data.csv"))

analysis_data |> 
  ggplot(aes(x = source_of_infection, fill = source_of_infection)) +
  geom_bar(stat = "count") +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 6),  
    plot.title = element_text(size = 100, face = "bold"),
    axis.title.x = element_text(size = 12),  
    axis.title.y = element_text(size = 15),
    strip.text = element_text(size = 20)
  ) +
  facet_wrap(~age_group, ncol = 1) +
  coord_flip() +
  labs(
    x = "Source of Infection",
    y = "Number of COVID-19 Cases",
    caption = "Data source: Open Toronto Data."
  )

```



\clearpage

\appendix

# Appendix {-}


# Additional data details



\newpage


# References


